### ISSUE TITLE
Thank you for this repository

### ISSUE THREAD

**Issue by Dylan-Duault** [douglaskataki/oscp-report-notes#1]
Thank you for making this repository public.
I forked it and began to make some changes to it so it better match my needs and preferences.

I wont create pull requests as I changed the structure and added things that might not interest you, but you want to check out my changes here is the fork

https://github.com/Dylan-Duault/oscp-report-notes

I just started editing it, so there is not much to see yet.
I'll change the readme very soon to give you credits.

Have a nice day!

**Comment by douglaskataki** [comment]
Salut Dylan! Merci pour ta message!

No worries! Use these at will and send me some messages if you find something wrong! 

Hope that these cheetsheat help you as they helped me in my journey through Pentesting.

Soon I will check your fork!

And thanks for the credits!
